authentication/urls.py
from django.urls import path
from authentication.views import signup, signin, signout

app_name = 'authentication'
urlpatterns = [
    path('signup/', signup, name= 'signup'),
    path('signin/', signin, name= 'signin'),
    path('signout/', signout, name= 'signout')

   
]

wiljeanApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView,  PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView



urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('gallery/', views.gallery, name='gallery'),
    path('download/', views.download, name='download'),
    path('blog/', views.blog, name='blog'),
    path('blog_detail/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('fetch_comments/<int:blog_id>/', views.fetch_comments, name='fetch_comments'),
    path('all_comment/<int:blog_id>/', views.all_comment, name='all_comment'),
    path('contact/', views.contact, name='contact'),
    path('download_music/<int:music_id>/', views.download_music, name='download_music'),
    path('download_other_music/<int:music_id>/', views.download_other_music, name='download_other_music'),
    path('play_mp3/<int:music_id>/<int:other_music_id>', views.play_mp3, name='play_mp3'),
    path('stream_audio/<int:music_id>/', views.stream_audio, name='stream_audio'),
    path('stream_other_audio/<int:music_id>/', views.stream_other_audio, name='stream_other_audio'),
    path('upload/', views.upload, name='upload'),
    path('music_details/<int:music_id>/', views.music_details, name='music_details'),
    path('all_music/', views.all_music, name='all_music'),
    path('blog_upload/', views.blog_upload, name='blog_upload'),
    path('edit_music/<int:music_id>/', views.edit_music, name='edit_music'),
    path('confirmation/<int:other_music_id>/<int:wil_id>/', views.confirmation, name='confirmation'),
    path('delete/<int:other_music_id>/<int:wil_id>/', views.delete, name='delete'),
    path('add_event/', views.add_event, name='add_event'),
    path('event_detail/<int:event_id>/', views.event_detail, name='event_detail'),
    path('fetch_event_comments/<int:event_id>/', views.fetch_event_comments, name='fetch_event_comments'),
    
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('other_music_detail/<int:other_id>/', views.other_music_detail, name='other_music_detail'),
    path('all_contacts/', views.all_contacts, name='all_contacts'),
    path('reply/<int:contact_id>/', views.reply, name='reply'),
    path('unsubscribe/<int:news_id>/', views.unsubscribe, name='unsubscribe'),
    path('delete_blog/<int:blog_id>/', views.delete_blog, name='delete_blog'),
    path('delete_blog_confirmation/<int:blog_id>/', views.delete_blog_confirmation, name='delete_blog_confirmation'),
    path('set_language/', views.set_language, name='set_language'),

   
]

wiljean_singing_ministry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView,  PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('wiljeanApp.urls')),
    path('rosetta/', include('rosetta.urls')),


    path('authentication/', include('authentication.urls')),
    path('cookie-consent/', include('cookie_consent.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # change password
    path('change-password/', PasswordChangeView.as_view(
        template_name ='wiljeanApp/auth/change-password.html'),   
        name='change-password'),
    path('change_password_done/', PasswordChangeDoneView.as_view(
        template_name ='wiljeanApp/auth/password_change_done.html'),   
        name='password_change_done'),

    #forget password
    path('password_reset/', PasswordResetView.as_view(template_name ='wiljeanApp/auth/password_reset.html'), 
        name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name ='wiljeanApp/auth/password_reset_done.html'), 
        name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name ='wiljeanApp/auth/password_reset_form.html', 
        ), 
        name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(template_name ='wiljeanApp/auth/password_reset_complete.html'),
        name='password_reset_complete'),

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiljeanApp/forms.py
from django import forms
from .models import Other_peoples_music, Blog, Subscription,EventComment, Events, replyContact, blogComment
from django.utils.translation import gettext_lazy as _
from parler.forms import TranslatableModelForm

class MusicForm(forms.ModelForm):
    class Meta:
        model = Other_peoples_music
        fields = ['title', 'artist', 'file', 'album', 'photo', 'location']

# class BlogForm(forms.ModelForm):
#     class Meta:
#         model = Blog
#         fields = ['title', 'content', 'image']


class BlogForm(TranslatableModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Translate form labels
        self.fields['title'].label = _('Title')
        self.fields['content'].label = _('Content')
        self.fields['image'].label = _('Image')

class EventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = ['title', 'body', 'image', 'author', 'date', 'time', 'address']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

class replyForm(forms.ModelForm):
    class Meta:
        model = replyContact
        fields = ['name', 'message']

class commentForm(forms.ModelForm):
    class Meta:
        model = blogComment
        fields = ['name', 'message']

class subtForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['email',]

class EventCommentForm(forms.ModelForm):
    class Meta:
        model = EventComment
        fields = ['name', 'message']

wiljeanApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . models import Slider,Quotes, Events, Blog, EventComment, blogComment, replyContact, WiljeanGallery, Gallery, Other_peoples_music, Blog, Album, ChooseUs, About, Subscription, Contact, Music
from django.contrib import messages
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
from django.conf import settings
from django.http import FileResponse
from django.http import StreamingHttpResponse
from django.urls import reverse
from django.utils import timezone
from django.db.models import Q
from wiljeanApp.search import search_music, newsletter
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.models import User
import os
from . forms import MusicForm, EventCommentForm, BlogForm, EventForm, replyForm, commentForm
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.serializers import serialize, deserialize
from django.utils.translation import activate

# Create your views here.

def unsubscribe(request, news_id):
    del_news = Subscription.objects.get(id = news_id)
    if del_news:
        del_news.delete()
        messages.info(request, 'You unsubcribe from our newsletter. If this is a mistake feel free to subscribe again')
        return redirect('index')

def index(request):
    slide = Slider.objects.all()
    quotes =Quotes.objects.all()
    event = Events.objects.all()
    choose = ChooseUs.objects.all()
    
    newsletter(request)
    
    context = {
        'slider':slide,
        'quotes':quotes,
        'events':event,
        'chooseus':choose
    }
    return render(request, 'wiljeanApp/index.html', context)

@login_required(login_url='authentication:signin')
def add_event(request):
    
    album = Album.objects.all()
    latest_music = Other_peoples_music.objects.all().order_by('-publish_date')[:5]
    form = EventForm(request.POST, request.FILES)
    
    if request.method =='POST':
        
        if form.is_valid():
            form.save()
            messages.info(request, 'Event added successfully')
            
            return JsonResponse({
                'success':True, 
                'message':'Event added successful'
                })
        
    newsletter(request)
    context = {
        'form':form,
        'albums':album,
        'latests':latest_music
    }
    
    return render(request, 'wiljeanApp/event_form.html', context)


def delete_event(request, event_id):
    event = Events.objects.get(id = event_id)
    if event.date < timezone.now().date():
        # If the event date has passed, delete the event
        event.delete()
        messages.info(request, 'This event has expired and has been deleted.')
        return redirect('index')
    return redirect(reverse('event_detail', args=[event_id]))


def event_detail(request, event_id):
    user= request.user
    event = Events.objects.get(id = event_id)
    
    if request.method =='POST':
        form = EventCommentForm(request.POST)
        if form.is_valid():
            if user.is_authenticated:
                save_form =form.save(commit = False)
                save_form.user = request.user
                save_form.event = event
                save_form.save()


                return JsonResponse({
                    'success':True,
                    'message':'You commented on this Event',
                    
                })
            
            save_form =form.save(commit = False)   
            save_form.event = event
            save_form.save()
            
            return JsonResponse({
                    'success':True,
                    'message':'You commented on this Event',
                    
                })

        
    newsletter(request)
    form = EventCommentForm()
    context= {
        'events':event,
        'form':form
    }
    return render(request, 'wiljeanApp/event_detail.html', context)

def fetch_event_comments(request, event_id):
    event = Events.objects.get(id=event_id)
    comments = EventComment.objects.filter(event=event).order_by('-date')[:8]

    serialize_comment = serialize('json', comments)
    deserialized_comments = list(deserialize('json', serialize_comment))
    
    comments_data = []
    
    # Iterate through each comment and add required fields to the list
    for deserialized_obj in deserialized_comments:
        comment = deserialized_obj.object
        user = comment.user.username if comment.user else comment.name
        
        comment_data = {
            'user': user,
            'text': comment.message,
            'date': comment.date.strftime('%Y-%m-%d')
        }
        comments_data.append(comment_data)

        print('this is the user printed', comments_data)
        print('User:', comment_data['user'])
    
    # Return the list of comments data as JSON response
    return JsonResponse({'comments': comments_data})

def about(request):
    abouts = About.objects.all()
    latest_music = Other_peoples_music.objects.all().order_by('-publish_date')[:8]

    album= Album.objects.all()

    newsletter(request)
    
    context = {
        'abouts':abouts,
        'albums':album,
        'latests':latest_music
    }
    return render(request, 'wiljeanApp/about.html', context)

def gallery(request):
    all_gallery = Gallery.objects.all()
    wil_gallery = WiljeanGallery.objects.all()
    newsletter(request)

    context = {
        'galleries':all_gallery,
        'wiljean': wil_gallery
    }
    
    return render(request, 'wiljeanApp/gallery.html', context)

def download(request):
    musics = Music.objects.all()
    other_music = Other_peoples_music.objects.all()
    # search = None
    searches = search_music(request)

    newsletter(request)
    context = {
        'musics': musics,
        'other_musics': other_music,
        'searches': searches,
    }
    return render(request, 'wiljeanApp/download.html', context)


def blog(request):
    # activate('ha')
    album = Album.objects.all()
    blog_list = Blog.objects.all().order_by('-publish_date')

    latest_music = Other_peoples_music.objects.all().order_by('-publish_date')[:8]

    paginator = Paginator(blog_list, 2)  # Show 5 blog posts per page

    page = request.GET.get('page')
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        blogs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        blogs = paginator.page(paginator.num_pages)

     # Get user's language preference from session or user profile
    user_language = request.session.get('user_language', 'en')  # Default to English if not set

    # Activate user's language
    # activate(user_language)

    newsletter(request)

    context = {
        'albums': album,
        'blogs': blogs,
        'latests':latest_music
    }
    request.session['last_visited_page'] = request.path
    return render(request, 'wiljeanApp/blog.html', context)


def set_language(request):
    if 'lang' in request.GET:
        language = request.GET['lang']
        request.session['user_language'] = language
        activate(language)
    # Redirect back to the referring page or a specific page
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required(login_url='authentication:signin')
def delete_blog(request, blog_id):
    user = request.user
    if user.is_authenticated and user.is_staff:
        blog = Blog.objects.get(id = blog_id)
        blog.delete()
        messages.info(request, 'Blog deleted!')
        return redirect('blog')
    messages.info(request, 'You are not permitted to delete this blog')
    return redirect('blog')
       
    
def delete_blog_confirmation(request, blog_id):
    return render(request, 'wiljeanApp/blog_confirmation.html', {'blog_id':blog_id })
  

    
class CustomJSONEncoder(DjangoJSONEncoder):
    def default(self, obj):
        if isinstance(obj, User):
            return str(obj)  # Use the string representation of the user
        return super().default(obj)

def blog_detail(request, blog_id):
    user = request.user
    album = Album.objects.all()
    blog = Blog.objects.get(id=blog_id)
    latest_music = Other_peoples_music.objects.all().order_by('-publish_date')[:8]
    comment = blogComment.objects.filter(blog=blog).order_by('-date')[:8]

    if request.method =='POST':
        form = commentForm(request.POST)
        if form.is_valid():
            if user.is_authenticated:
                save_form =form.save(commit = False)
                save_form.user = request.user
                save_form.blog = blog
                save_form.save()


                return JsonResponse({
                    'success':True,
                    'message':'You commented on this post',
                    
                })
            
            save_form =form.save(commit = False)   
            save_form.blog = blog
            save_form.save()
            
            return JsonResponse({
                    'success':True,
                    'message':'You commented on this post',
                    
                })

    # Set the session variable
    request.session['last_visited_page'] = request.path

    print("Session Data:", dict(request.session))

    newsletter(request)

    form = commentForm()

    context = {
        'blogs': blog,
        'albums': album,
        'latests':latest_music,
        'form':form,
        
    }

    return render(request, 'wiljeanApp/blog_detail.html', context)



def fetch_comments(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    comments = blogComment.objects.filter(blog=blog).order_by('-date')[:8]

wiljeanApp/templates/wiljeanApp/base/about_sidebar.html
{% load static %}
<div class="col-md-4 col-md-push-1">
    <aside class="sidebar">
        <div class="widget">
            <h3 class="widget-title">Discography</h3>
            
            <ul class="discography-list">
                {% for album in albums %}
                <li>
                    <figure class="cover"><img src="{{ album.cover.url }}" alt="thumbnail 1"></figure>
                    <div class="detail">
                        <h3><a href="{% url 'music_details' album.id %}">{{ album.name }}</a></h3>
                        <span class="year">{{ album.year_of_publish}}</span>
                        <span class="track">{{ album.tracks }} tracks</span>
                    </div>
                </li>
                {% endfor %}
                <h3 class="widget-title">Latest Music</h3>
                {% for latest in latests %}
                <li>
                    <figure class="cover"><img src="{{ latest.photo.url }}" alt="thumbnail 1"></figure>
                    <div class="detail">
                        <h3><a href="{% url 'other_music_detail' latest.id %}">{{ latest.title }} - by {{ latest.artist }}</a></h3>
                        <span class="year">{{other.publish_date|date:"Y"}}</span>
                        <span class="track">{{ album.tracks }} mp3</span>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </aside>
</div>

wiljeanApp/templates/wiljeanApp/base/address_base.html
<div class="col-md-6">
    <div class="map-wrapper">
        <div class="map"></div>
        <address>
            <div class="row">
                <div class="col-sm-6">
                    <strong>Wiljean Singing Ministry.</strong>
                    <span>Dafa - Kwali Area Council, FCT Abuja</span>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'contact' %}">mathiaswilfred7@yahoo.com</a> <br>
                    <a href="{% url 'contact' %}">+234 8134622388</a>
                </div>
            </div>
        </address>
    </div>
</div>

wiljeanApp/templates/wiljeanApp/base/audio_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Wiljean Ministry |{% block title %}{% endblock %}</title>
		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900" rel="stylesheet" type="text/css">
		<!-- <link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
		<!-- <link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css"> -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="{% static 'style.css' %}">
		<link rel="stylesheet" href="{% static 'audio.css' %}">
		<script src="{% static 'js/audio.js' %}"></script>
		
		

	</head>
<body class="header-collapse">
{% block content %}{% endblock %}

	

</body>
</html>

wiljeanApp/templates/wiljeanApp/base/base.html
{% load static %}
{% load cookie_consent_tags %}


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>Wiljean Ministry |{% block title %}{% endblock %}</title>
		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900" rel="stylesheet" type="text/css">
		<!-- <link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
		<link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="{% static 'style.css' %}">
		<link rel="stylesheet" href="{% static 'cookie.css' %}">
		<!-- Include Axios from a CDN -->
		<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
		<!-- Include jQuery from Google CDN -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


		
		
		<script>
			$(document).ready(function(){
			// Function to close the alert when close button is clicked
			document.addEventListener('DOMContentLoaded', function() {
				document.querySelectorAll('.alert .close').forEach(function(closeBtn) {
					closeBtn.addEventListener('click', function() {
						this.closest('.alert').style.display = 'none';
					});
				});
			});
		
});
</script>
<style>
.notification-container {
    position: fixed;
    top: 0%;
    left: 45%;
    /* transform: translate(-50%, -50%); */
    text-align: center;
    z-index: 10;
    color: red; /* Red text color */
}


	.alert {
		margin-bottom: 10px;
	}

	.close {
		position: absolute;
		top: 0;
		right: 0;
		padding: 5px 10px;
		background-color: transparent;
		border: none;
		cursor: pointer;
	}

	.search-form {
    margin-top: 50px;
    text-align: center;
}

.search-form .form-control {
    border-radius: 30px;
    padding: 15px;
    font-size: 16px;
    border-color: #ddd;
    box-shadow: none;
}

.search-form .btn-primary {
    border-radius: 30px;
    padding: 14px 30px;
    font-size: 16px;
    background-color: #4CAF50;
    border-color: #4CAF50;
}

.search-form .btn-primary:hover {
    background-color: #45a049;
    border-color: #45a049;
}

</style>

	</head>
<body class="header-collapse">
	<div id="cookie-consent">
		<p>This website uses cookies to ensure you get the best experience on our website.</p>
		<button id="accept-cookies">Accept Cookies</button>
		<button id="decline-cookies">Decline Cookies</button>
	</div>


	<header class="site-header">
		<div class="container">
			<a href="{% url 'index' %}" id="branding">
				<img src="{% static 'dummy/WhatsApp Image 2024-04-01 at 10.41.04 AM.jpeg' %}" alt="Site Title" style="width:80px; height:60px;">
				<small class="site-description">A gift to the world</small>
			</a> <!-- #branding -->
			
			<nav class="main-navigation">
				<button type="button" class="toggle-menu"><i class="fa fa-bars"></i></button>
				<ul class="menu">
					<li class="menu-item current-menu-item"><a href="{% url 'index' %}">Home</a></li>
					<li class="menu-item"><a href="{% url 'about' %}">About</a></li>
					<li class="menu-item"><a href="{% url 'gallery' %}">Gallery</a></li>
					<li class="menu-item"><a href="{% url 'download' %}">Download</a></li>
					<li class="menu-item"><a href="{% url 'blog' %}">Blog</a></li>
					<li class="menu-item"><a href="{% url 'upload' %}">Upload</a></li>
					<li class="menu-item"><a href="{% url 'contact' %}">Contact</a></li>
					<li class="menu-item"><a href="{% url 'add_event' %}">Add event</a></li>
					{% if not user.is_authenticated %}
					<li class="menu-item"><a href="{% url 'authentication:signin' %}">Login</a></li>
					
					{% endif %}
					{% if user.is_authenticated %}
					<li class="menu-item"><a href="{% url 'authentication:signout' %}">Hi {{user}}! Logout</a></li>
					
					{% endif %}
					{% if user.is_staff %}
					<li class="menu-item"><a href="{% url 'blog_upload' %}">Create Blog</a></li>
					{% endif %}
				</ul> <!-- .menu -->
			</nav> <!-- .main-navigation -->
			<div class="mobile-menu"></div>

		</div>
	</header> <!-- .site-header -->
	<!-- Notification Message Container -->
    <div class="notification-container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-dismissible alert-{{ message.tags }}">
            <button type="button" class="button close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <!-- End Notification Message Container -->
	
	

	{% block content %}
	{% endblock %}

	<footer class="site-footer">
		<div class="container">
			<img src="{% static 'dummy/logo-footer.png' %}" alt="Site Name">
			
			<address>
				<p>St. Johnbosco Dafa, Kwali Area Council. FCT Abuja <br>
					<a href="">+234 8134622388</a> <br>
					<a href="{% url 'contact' %}">mathiaswilfred7@yahoo.com</a></p> 
			</address> 
			
			<form action="." method="POST" class="newsletter-form">
				{% csrf_token %}
				<input type="email" name = "email" placeholder="Enter your email to join newsletter...">
				<input type="submit" class="button cut-corner" value="Subscribe">
			</form> <!-- .newsletter-form -->
			
			<div class="social-links">
				<a href="#"><i class="fa fa-facebook-square"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-google-plus"></i></a>
				<a href="#"><i class="fa fa-pinterest"></i></a>
			</div> <!-- .social-links -->
			
			<p class="copy">Copyright 2014 Wiljean Ministry. Designed by Wilfred. All right reserved</p>
		</div>
	</footer> <!-- .site-footer -->


	<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
	<script src="{% static 'js/plugins.js' %}"></script>
	<script src="{% static 'js/app.js' %}"></script>
	<script src="{% static 'js/audio.js' %}"></script>
	<script src="{% static 'js/cookie.js' %}"></script>
	<script src="{% static 'js/jssubmission.js' %}"></script>

</body>
</html>

wiljeanApp/templates/wiljeanApp/base/base_about.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
		
		<title>About Us| Band Template</title>
		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900" rel="stylesheet" type="text/css">
		<link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="style.css">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>

	<body>

		<script src="js/jquery-1.11.1.min.js"></script>		
		<script src="js/plugins.js"></script>
		<script src="js/app.js"></script>
		
	</body>

</html>

wiljeanApp/templates/wiljeanApp/base/confirmation_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            padding-top: 50px;
        }
        .card {
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .card-header {
            background-color: #343a40;
            color: #fff;
            border-radius: 10px 10px 0 0;
        }
        .card-body {
            padding: 30px;
        }
        .btn-danger {
            background-color: #dc3545;
            border-color: #dc3545;
        }
        .btn-danger:hover {
            background-color: #c82333;
            border-color: #bd2130;
        }
        .btn-secondary {
            background-color: #6c757d;
            border-color: #6c757d;
        }
        .btn-secondary:hover {
            background-color: #5a6268;
            border-color: #545b62;
        }
    </style>
</head>
<body>
    {% block content %}{% endblock %}
    <!-- Bootstrap JS (Optional, if you need JavaScript functionality) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</body>
</html>

wiljeanApp/templates/wiljeanApp/base/search_base.html
<form action="." method="get" class="search-form">
    <div class="input-group">
        <input type="text" name="query" class="form-control" placeholder="Enter keyword...">
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>
</form>