wiljeanApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView,  PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView



urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('gallery/', views.gallery, name='gallery'),
    path('download/', views.download, name='download'),
    path('blog/', views.blog, name='blog'),
    path('blog_detail/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('fetch_comments/<int:blog_id>/', views.fetch_comments, name='fetch_comments'),
    path('all_comment/<int:blog_id>/', views.all_comment, name='all_comment'),
    path('contact/', views.contact, name='contact'),
    path('download_music/<int:music_id>/', views.download_music, name='download_music'),
    path('download_other_music/<int:music_id>/', views.download_other_music, name='download_other_music'),
    path('play_mp3/<int:music_id>/<int:other_music_id>', views.play_mp3, name='play_mp3'),
    path('stream_audio/<int:music_id>/', views.stream_audio, name='stream_audio'),
    path('stream_other_audio/<int:music_id>/', views.stream_other_audio, name='stream_other_audio'),
    path('upload/', views.upload, name='upload'),
    path('music_details/<int:music_id>/', views.music_details, name='music_details'),
    path('all_music/', views.all_music, name='all_music'),
    path('blog_upload/', views.blog_upload, name='blog_upload'),
    path('edit_music/<int:music_id>/', views.edit_music, name='edit_music'),
    path('confirmation/<int:other_music_id>/<int:wil_id>/', views.confirmation, name='confirmation'),
    path('delete/<int:other_music_id>/<int:wil_id>/', views.delete, name='delete'),
    path('add_event/', views.add_event, name='add_event'),
    path('event_detail/<int:event_id>/', views.event_detail, name='event_detail'),
    path('fetch_event_comments/<int:event_id>/', views.fetch_event_comments, name='fetch_event_comments'),
    
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('other_music_detail/<int:other_id>/', views.other_music_detail, name='other_music_detail'),
    path('all_contacts/', views.all_contacts, name='all_contacts'),
    path('reply/<int:contact_id>/', views.reply, name='reply'),
    path('unsubscribe/<int:news_id>/', views.unsubscribe, name='unsubscribe'),
    path('delete_blog/<int:blog_id>/', views.delete_blog, name='delete_blog'),
    path('delete_blog_confirmation/<int:blog_id>/', views.delete_blog_confirmation, name='delete_blog_confirmation'),
    path('set_language/', views.set_language, name='set_language'),

   
]

wiljean_singing_ministry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView,  PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('wiljeanApp.urls')),
    path('rosetta/', include('rosetta.urls')),


    path('authentication/', include('authentication.urls')),
    path('cookie-consent/', include('cookie_consent.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # change password
    path('change-password/', PasswordChangeView.as_view(
        template_name ='wiljeanApp/auth/change-password.html'),   
        name='change-password'),
    path('change_password_done/', PasswordChangeDoneView.as_view(
        template_name ='wiljeanApp/auth/password_change_done.html'),   
        name='password_change_done'),

    #forget password
    path('password_reset/', PasswordResetView.as_view(template_name ='wiljeanApp/auth/password_reset.html'), 
        name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name ='wiljeanApp/auth/password_reset_done.html'), 
        name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name ='wiljeanApp/auth/password_reset_form.html', 
        ), 
        name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(template_name ='wiljeanApp/auth/password_reset_complete.html'),
        name='password_reset_complete'),

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiljeanApp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
# from parler.models import TranslatableModel, TranslatedFields
from parler.models import TranslatableModel, TranslatedFields
# Create your models here.

class Slider(models.Model):
    header = models.CharField(max_length = 255)
    title = models.CharField(max_length = 255)
    body = models.CharField(max_length =255)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'slider'

class Quotes(models.Model):
    author = models.CharField(max_length =255)
    body = models.CharField(max_length =500)
    more_info = models.CharField(max_length =255, null = True)

    def __str__(self):
        return self.author
    class Meta:
        db_table = 'quote'
        

class Events(models.Model):
    title = models.CharField(max_length =255)
    body = models.TextField(max_length =1500)
    image = models.ImageField(upload_to='media', null = True)
    author = models.CharField(max_length =255, null = True)
    address = models.CharField(max_length =500, null = True)
    time = models.CharField(max_length =255, null = True)
    date = models.DateField(default =timezone.now)

    def __str__(self):
        return self.title

    def ImageUrl(self):
        if self.image:
            return self.image.url
        else:
            return None


    class Meta:
        db_table = 'events'


class ChooseUs(models.Model):
    title = models.CharField(max_length =255)
    body = models.CharField(max_length =1500)
    image = models.ImageField(upload_to='media')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'choose us'
class About(models.Model):
    title = models.CharField(max_length =255)
    body = models.TextField(max_length =10000)
    image = models.ImageField(upload_to='media')

    def __str__(self):
        return self.title

class Subscription(models.Model):
    email = models.EmailField(max_length = 255)
    date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.email

    class Meta:
        db_table = 'subscription'

class Contact(models.Model):
    name = models.CharField(max_length =255)
    email = models.EmailField(max_length = 255)
    message =models.TextField(max_length =1000)
    date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name
    

    class Meta:
        db_table = 'contact'

class replyContact(models.Model):
    name = models.CharField(max_length =255)
    date = models.DateTimeField(auto_now_add=True)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    message =models.TextField(max_length =1000)
    reply = models.BooleanField(default=False)


    def __str__(self):
        return self.name
    

class Album(models.Model):
    name =models.CharField(max_length = 255)
    tracks = models.IntegerField(default = 0)
    year_of_publish = models.DateField()
    cover = models.ImageField(upload_to='media', null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'album'


class Music(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    file = models.FileField(upload_to='music_files')
    album = models.ForeignKey(Album, on_delete = models.CASCADE, null =True)
    publish_date = models.DateField()


    def __str__(self):
        return self.title
    
    class Meta:
        db_table = 'music'

class Blog(TranslatableModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    publish_date=models.DateTimeField(auto_now_add=True)
    translations = TranslatedFields(
        title=models.CharField(_('title'), max_length=100),
        content=models.TextField(_('content'), max_length=10000),
        image=models.ImageField(_('image'), upload_to='music_files'),
        
    )

    def save_image_to_galary(self):
        Gallery.objects.create(photo = self.image)

    def __str__(self):
        return self.title
    class Meta:
        db_table = 'blog'
    
class Other_peoples_music(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    file = models.FileField(upload_to='music_files')
    album = models.CharField(max_length=100)
    publish_date = models.DateTimeField(auto_now = True)
    location = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='image_file', null=True)

    def save_image_to_galary(self):
        Gallery.objects.create(photo = self.photo)

    def __str__(self):
        return self.title
    
    class Meta:
        db_table = 'other_music'

class Gallery(models.Model):
    photo = models.ImageField(upload_to='image_file')

    class Meta:
        ordering = ('-photo',)

class WiljeanGallery(models.Model):
    photo = models.ImageField(upload_to='image_file')

    class Meta:
        ordering = ('-photo',)

class blogComment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    name = models.CharField(max_length=100, null = True, blank=True)
    message = models.TextField(max_length=100)
    blog =models.ForeignKey(Blog, on_delete = models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message


class EventComment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    name = models.CharField(max_length=100, null = True, blank=True)
    message = models.TextField(max_length=100)
    event =models.ForeignKey(Events, on_delete = models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

wiljeanApp/forms.py
from django import forms
from .models import Other_peoples_music, Blog, Subscription,EventComment, Events, replyContact, blogComment
from django.utils.translation import gettext_lazy as _
from parler.forms import TranslatableModelForm

class MusicForm(forms.ModelForm):
    class Meta:
        model = Other_peoples_music
        fields = ['title', 'artist', 'file', 'album', 'photo', 'location']

# class BlogForm(forms.ModelForm):
#     class Meta:
#         model = Blog
#         fields = ['title', 'content', 'image']


class BlogForm(TranslatableModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Translate form labels
        self.fields['title'].label = _('Title')
        self.fields['content'].label = _('Content')
        self.fields['image'].label = _('Image')

class EventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = ['title', 'body', 'image', 'author', 'date', 'time', 'address']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

class replyForm(forms.ModelForm):
    class Meta:
        model = replyContact
        fields = ['name', 'message']

class commentForm(forms.ModelForm):
    class Meta:
        model = blogComment
        fields = ['name', 'message']

class subtForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['email',]

class EventCommentForm(forms.ModelForm):
    class Meta:
        model = EventComment
        fields = ['name', 'message']

wiljeanApp/templates/wiljeanApp/blog_detail.html
{% extends 'wiljeanApp/base/base.html' %}
{% load static %}

{% block title %} Blog {% endblock %}

{% block content %}    
<main class="main-content" style="padding-top: 100px;">
    <div class="fullwidth-block inner-content">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <div class="content">
                        <h2 class="entry-title">Blog Detail</h2>
                        
                        <div class="post">
                            <div class="entry-date">
                                <div class="date">{{ blogs.publish_date|date:'d' }}</div>
                                <span class="month">{{ blogs.publish_date|date:'M' }}</span>
                            </div>
                            <div class="featured-image">
                                <img src="{{ blogs.image.url }}" alt="" style="height:600px;">
                            </div>
                            <h2 class="entry-title"><a href="">{{ blogs.title }}</a></h2>
                            <p>{{ blogs.content | safe }}</p>
                            
                        </div>
                        

						
                    </div>
                </div>
                {% include 'wiljeanApp/base/about_sidebar.html' %}
            </div>
                    <!-- comment section -->
        <div class="row">
            <div class="col-md-6">
                <div class="notification-container" id="notification_message">
                    <!-- notification goes here -->
                    
                </div>
                <h2 class="page-title ">Leave a comment</h2>
                <form action="." method = "post" class="contact-form" id="commentForm">
                    {% csrf_token %}
                    {% if not user.is_authenticated %}
                    <div class="form-group">
                        <label for="id_title">Name:</label>
                        {{ form.name }}
                        {% for error in form.name.errors %}
                        <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                    
                    <div class="form-group">
                        <label for="id_title">Message:</label>
                        {{ form.message }}
                        {% for error in form.message.errors %}
                        <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <input type="submit" value="Post Comment">
                    
                </form>
            </div>
            
        </div>
        <!-- end of comment -->
        <!-- comments -->
        
        <div class="col-md-10 col-md-push-1">
            <aside class="sidebar">
                <div class="widget">
                    {% if comments %}
                    <h3 class="widget-title">All comment</h3>
                    {% endif %}

                    <ul class="discography-list" id = "commentid">
                        
                        <!-- comment goes here -->
                    </ul>
                    
                </div>
            </aside>
        </div>

        <!-- end -->
        </div>

    </div> <!-- .testimonial-section -->
</main> <!-- .main-content -->

<script>
    $(document).ready(function(){
    function loadComments() {
    $.ajax({
        url: "{% url 'fetch_comments' blogs.id %}",
        type: 'GET',
        success: function(response){
            let commentsHTML = '';

                for (let i = 0; i < response.comments.length; i++) {
                    let comment = response.comments[i];

                    // Access user data directly from the comment object
                    let name =comment.name ? comment.name : comment.user;

                    // Construct HTML for the comment
                    commentsHTML += `<li>
                        <div class="detail">
                            <span class="year">${comment.text}</span>
                            <span class="track">By: ${name} | ${comment.date}</span><br>
                        </div>
                    </li>`;
                }
            // }

            $("#commentid").html(commentsHTML); // Replace existing comments with new ones
        },
        error: function(xhr, status, error){
            console.log(status, error);
        }
    });
}

loadComments();

      
       
    $("#commentForm").submit(function(e){
        e.preventDefault();
        $.ajax({
            url: $(this).attr('action'),
            type: $(this).attr('method'),
            data: $(this).serialize(),
            success: function(response){
                // Load comments again after successful comment submission
                loadComments();
                

                $('#notification_message').html(`<div class="alert alert-success">${response.message}</div>`);
                // Optionally, you can reset the form
                $('#commentForm')[0].reset();
            },
            error: function(xhr, status, error){
                console.log(status, error)
                $('#notification_message').html('<div class="alert alert-danger">Error: ' + status + '</div>');
            }
        });
    });

    // SUBSCRIPTION
    $("#subForm").submit(function(e){
        e.preventDefault();
        
        // Get the CSRF token value
        var csrfToken = $('input[name="csrfmiddlewaretoken"]').val();
        
        $.ajax({
            url: $(this).attr('action'),
            type: $(this).attr('method'),
            processData: false,
            contentType: false,
            
            // Include the CSRF token in the data
            data: $(this).serialize() + "&csrfmiddlewaretoken=" + csrfToken,
            success: function(data){
                if(data.success){
                    console.log('Submitted', data.message);                  
                } else {
                    console.log('fail', data.message);
                }
            },
            error: function(xhr, status, error){
                console.log(status, error);
            }
        });
    });
    

});
</script>
    {% endblock %}

wiljeanApp/templates/wiljeanApp/blogform.html
{% extends 'wiljeanApp/base/base.html' %}

{% block title %} Upload {% endblock %}

{% block content %}
<main class="main-content " style="padding-top: 50px;">
    <div class="fullwidth-block inner-content">
        <div class="container">
            <h2 class="page-title ">Create Blog</h2>
            
            <div class="row">
                <div class="col-md-6">
                    <form method="post" action="{% url 'blog_upload' %}" enctype="multipart/form-data" class="contact-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Title:</label>
                            {{ form.title }}
                            {% for error in form.title.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_title">Content:</label>
                            {{ form.content | safe}}
                            {% for error in form.content.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_music">Image:</label>
                            {{ form.image }}
                            <small class="text-muted">Maximum file size: 10MB</small>
                            {% for error in form.image.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>

                        
                        <input type="submit" value="Create Blog" class="btn btn-primary">
                    </form>
                </div>
                <div class="col-md-6">
                    <!-- Your contact information -->
                </div>
            </div>
        </div>
    </div>
</main>
<script>
    document.getElementById("id_music").addEventListener("change", function () {
        const fileInput = this;
        if (fileInput.files.length > 0) {
            const fileSize = fileInput.files[0].size; // in bytes
            const maxSize = 10 * 1024 * 1024; // 10MB
            if (fileSize > maxSize) {
                alert("File size exceeds the limit (10MB).");
                fileInput.value = ""; // Clear the input
            }
        }
    });
</script>
{% endblock %}



{% comment %}
{% extends 'wiljeanApp/base/base.html' %}

{% block title %} Upload {% endblock %}

{% block content %}
<main class="main-content " style="padding-top: 50px;">
    <div class="fullwidth-block inner-content">
        <div class="container">
            <h2 class="page-title ">Upload your Music</h2>
            {% if messages %}
                {% for message in messages %}
                <div class=" alert alert-dismissible alert-{{ message.tags }}">
                    <button type="button" class="button close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            <div class="row">
                <div class="col-md-6">
                    <form method="post" action="." enctype="multipart/form-data" class="contact-form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Upload Music" class="btn btn-primary">
                    </form>
                </div>
                <div class="col-md-6">
                    <!-- Your contact information -->
                </div>
            </div>
        </div>
    </div>
</main>
<script>
    document.getElementById("music").addEventListener("change", function () {
        const fileInput = this;
        if (fileInput.files.length > 0) {
            const fileSize = fileInput.files[0].size; // in bytes
            const maxSize = 10 * 1024 * 1024; // 10MB
            if (fileSize > maxSize) {
                alert("File size exceeds the limit (10MB).");
                fileInput.value = ""; // Clear the input
            }
        }
    });
</script>
{% endblock %}
{% endcomment %}

wiljeanApp/templates/wiljeanApp/edit.html
{% extends 'wiljeanApp/base/base.html' %}

{% block title %} Upload {% endblock %}

{% block content %}
<main class="main-content " style="padding-top: 50px;">
    <div class="fullwidth-block inner-content">
        <div class="container">
            <h2 class="page-title ">Edit your Music</h2>
            
            <div class="row">
                <div class="col-md-6">
                    <form method="post" action="." enctype="multipart/form-data" class="contact-form" id="editForm">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Title:</label>
                            {{ form.title }}
                            {% for error in form.title.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_title">Artist:</label>
                            {{ form.artist }}
                            {% for error in form.artist.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_music">Music File:</label>
                            {{ form.file }}
                            <small class="text-muted">Maximum file size: 10MB</small>
                            {% for error in form.file.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>

                        <div class="form-group">
                            <label for="id_album">Album:</label>
                            {{ form.album }}
                            {% for error in form.album.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_music">Photo:</label>
                            {{ form.photo }}
                            
                            {% for error in form.photo.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_location">Location:</label>
                            {{ form.location }}
                            {% for error in form.location.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <input type="submit" value="Upload Music" class="btn btn-primary">
                    </form>
                </div>
                <div class="col-md-6">
                    <!-- Your contact information -->
                </div>
            </div>
        </div>
    </div>
</main>
<script>
    $(document).ready(function(){
        $("#editForm").submit(function(event){
            event.preventDefault();
            let formData =new FormData($(this)[0]);
            let url = "{% url 'download' %}"

            $.ajax({
                url: $(this).attr("action"),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                // contentType:JSON,
                // processData:false,
                success: function(response){
                    if(response.success){
                        console.log('Updated successfull', response.message)
                        window.location.href = url;

                    }else{
                        console.log('Fail', response.message)
                        // window.location.href = url;
                    }
                },
                error: function(error){
                    console.log(error)
                }
            });

        });

    
        document.getElementById("id_music").addEventListener("change", function () {
            const fileInput = this;
            if (fileInput.files.length > 0) {
                const fileSize = fileInput.files[0].size; // in bytes
                const maxSize = 10 * 1024 * 1024; // 10MB
                if (fileSize > maxSize) {
                    alert("File size exceeds the limit (10MB).");
                    fileInput.value = ""; // Clear the input
                }
            }
        });
    });
</script>
{% endblock %}

wiljeanApp/templates/wiljeanApp/upload.html
{% extends 'wiljeanApp/base/base.html' %}

{% block title %} Upload {% endblock %}

{% block content %}
<main class="main-content " style="padding-top: 50px;">
    <div class="fullwidth-block inner-content">
        <div class="container">
            <h2 class="page-title ">Upload your Music</h2>
            <div class="notification-container" id="notification_message">
				<!-- notification goes here -->
				
			</div>
            
            <div class="row">
                <div class="col-md-6">
                    <form method="post" action ="{% url 'upload' %}" enctype="multipart/form-data" class="contact-form" id="uploadForm">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Title:</label>
                            {{ form.title }}
                            {% for error in form.title.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_title">Artist:</label>
                            {{ form.artist }}
                            {% for error in form.artist.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_music">Music File:</label>
                            {{ form.file }}
                            <small class="text-muted">Maximum file size: 10MB</small>
                            {% for error in form.file.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>

                        <div class="form-group">
                            <label for="id_album">Album:</label>
                            {{ form.album }}
                            {% for error in form.album.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_music">Photo:</label>
                            {{ form.photo }}
                            
                            {% for error in form.photo.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_location">Location:</label>
                            {{ form.location }}
                            {% for error in form.location.errors %}
                            <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <input type="submit" value="Upload Music" class="btn btn-primary">
                    </form>
                </div>
                <div class="">
                    <!-- Your contact information -->
                    {% include 'wiljeanApp/base/about_sidebar.html' %}
                </div>
            </div>
        </div>
    </div>
</main>
<script>
    $(document).ready(function() {
        
        document.getElementById("id_music").addEventListener("change", function () {
        const fileInput = this;
        if (fileInput.files.length > 0) {
            const fileSize = fileInput.files[0].size; // in bytes
            const maxSize = 10 * 1024 * 1024; // 10MB
            if (fileSize > maxSize) {
                alert("File size exceeds the limit (10MB).");
                fileInput.value = ""; // Clear the input
            }
        }
    });
    });
</script>{% endblock %}